/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#9a3c4d",
        "primary-fixed": "#ffd9dd",
        "primary-container": "#b95465",
        secondary: "#655c5d",
        "secondary-fixed": "#ece0e1",
        "secondary-container": "#e9ddde",
        "tertiary-fixed": "#f1dee0",
        "tertiary-container": "#807173",
        surface: "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "outline-variant": "#dbc0c2",
        "outline": "#887274",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#554244",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#400012",
        "on-primary-fixed-variant": "#7f2739",
        "background": "#fcf9f8",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#313030",
        "surface-tint": "#9d3e50",
      },
      spacing: {
        "sidebar-width": "240px",
        "topbar-height": "64px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "margin-desktop": "32px",
        "gutter": "16px",
        "bottom-bar-height": "64px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      fontSize: {
        "headline-xl": ["32px", { fontWeight: "700" }],
        "headline-lg": ["24px", { fontWeight: "700" }],
        "headline-md": ["20px", { fontWeight: "700" }],
        "body-lg": ["16px", { fontWeight: "400" }],
        "label-md": ["14px", { fontWeight: "600" }],
        "label-sm": ["12px", { fontWeight: "600" }],
        "body-md": ["14px", { fontWeight: "400" }],
      },
      fontFamily: {
        "sans": ["'Inter', sans-serif"],
      },
    },
  },
  darkMode: "class",
  plugins: [],
}
